# Generated by Django 5.2 on 2025-04-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sys_user',
        ),
    ]
